import { z } from "zod";

const envSchema = z.object({
  NEXTAUTH_SECRET: z.string().min(1),
  NEXTAUTH_URL: z.string().url(),
  // GOOGLE_CLIENT_ID: z.string().min(1),
  // GOOGLE_CLIENT_SECRET: z.string().min(1),
  DATABASE_URL: z.string().min(1),
  DIRECT_URL: z.string().min(1),
  NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
  NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1),
  SUPABASE_SERVICE_ROLE_KEY: z.string().min(1),
  // SSLCOMMERZ_STORE_ID: z.string().min(1),
  // SSLCOMMERZ_STORE_PASS: z.string().min(1),
  // SSLCOMMERZ_IS_LIVE: z.enum(["true", "false"]),
  // BKASH_APP_KEY: z.string().min(1),
  // BKASH_APP_SECRET: z.string().min(1),
  // BKASH_USERNAME: z.string().min(1),
  // BKASH_PASSWORD: z.string().min(1),
  // BKASH_BASE_URL: z.string().url(),
  // RESEND_API_KEY: z.string().min(1),
  NEXT_PUBLIC_APP_URL: z.string().url(),
});

export const env = envSchema.parse({
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  DATABASE_URL: process.env.DATABASE_URL,
  DIRECT_URL: process.env.DIRECT_URL,
  NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
  NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
  SSLCOMMERZ_STORE_ID: process.env.SSLCOMMERZ_STORE_ID,
  SSLCOMMERZ_STORE_PASS: process.env.SSLCOMMERZ_STORE_PASS,
  SSLCOMMERZ_IS_LIVE: process.env.SSLCOMMERZ_IS_LIVE,
  BKASH_APP_KEY: process.env.BKASH_APP_KEY,
  BKASH_APP_SECRET: process.env.BKASH_APP_SECRET,
  BKASH_USERNAME: process.env.BKASH_USERNAME,
  BKASH_PASSWORD: process.env.BKASH_PASSWORD,
  BKASH_BASE_URL: process.env.BKASH_BASE_URL,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
});
